USE [SGIPA]
GO

ALTER TABLE TB_MARCANTES ADD VOLUMES INT
GO

ALTER TABLE TB_MARCANTES ADD AUTONUM_CS_YARD INT
GO


USE [OPERADOR]
GO

/****** Object:  View [dbo].[VW_INVENT_ARMAZEM]    Script Date: 06/01/2015 19:02:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

DROP VIEW [dbo].[VW_INVENT_ARMAZEM]
GO

CREATE VIEW [dbo].[VW_INVENT_ARMAZEM]
AS
SELECT DISTINCT
	Y.ARMAZEM AS AUTONUM_ARMAZEM,
	A.DESCR AS DESCR_ARMAZEM,
	B.NUMERO AS BL,
	C.BL AS LOTE,
	Y.QUANTIDADE AS QTDE,
	E.DESCR AS EMBALAGEM,
	C.MERCADORIA,
	C.MARCA,
	P.RAZAO AS IMPORTADOR,
	N.DESCR AS NAVIO,
	V.VIAGEM,
	CASE WHEN CNTR.DT_ENTRADA IS NULL THEN CONVERT(CHAR,C.DT_ENTRADA,106) ELSE CONVERT(CHAR,CNTR.DT_ENTRADA,106) END AS data_entrada,
	CNTR.DT_INICIO_DESOVA AS DATA_DESOVA,
	CNTR.ID_CONTEINER AS CNTR_DESOVA,
	ISNULL(C.PESO_BRUTO,0) AS peso,
	ISNULL(C.VOLUME_M3,0) AS VOLUME,
	Y.YARD AS POSICAO,
	'IPA-CS' AS FINALITY,
	ISNULL(TD.DESCR,'NOT DEFINED YET') AS TIPO_DOC,
	ISNULL(B.CANAL_SISCOMEX,0) AS CANAL_ALF,
	 CASE
			WHEN (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END) < 2 then '00-02 days'
			WHEN (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END) >= 2 and (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END)<4  then '02-04 days'
			WHEN (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END) >= 4 and (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END)<6  then '04-06 days'
			WHEN (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END) >= 6 and (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END)<8  then '06-08 days'
			WHEN (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END) >= 8 and (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END)<12  then '08-12 days'
			WHEN (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END) >= 12 and (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END)<20  then '12-20 days'
			WHEN (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END) >= 20 and (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END)<30  then '20-30 days'
			WHEN (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END) >= 30 and (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END)<45  then '30-45 days'
			WHEN (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END) >= 45 and (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END)<60  then '45-60 days'
			WHEN (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END) >= 60   then '60 or + days'
	END
		AS dias_arm_faixa,
	CASE WHEN B.SEQ_FMA IS NULL THEN 0 ELSE 1 END AS FLAG_FMA,
	CASE WHEN B.TG IS NULL THEN 0 ELSE 1 END AS FLAG_TG,
	'' AS MOTIVO_PROX_MVTO,
	NULL AS HORAS_PROX_MVTO,
	'I' AS SISTEMA,
	'Y' + RTRIM(LTRIM (CONVERT(CHAR,Y.AUTONUM))) AS ID_GRAVACAO,
    C.IMO AS IMO ,
    VW2.NVOCC AS NVOCC,
    C.QUANTIDADE AS QTDE_CAPTADA,
	ISNULL(M.AUTONUM,0) AS MARCANTE,
	ISNULL(M.AUTONUM_CS_YARD,0) AS AUTONUM_CS_YARD
FROM
	SGIPA..TB_CARGA_SOLTA C INNER JOIN
	SGIPA..TB_BL B ON C.BL=B.AUTONUM INNER JOIN 
	SGIPA..TB_CARGA_SOLTA_YARD Y ON C.AUTONUM = Y.AUTONUM_CS LEFT JOIN
	SGIPA..DTE_TB_EMBALAGENS E ON C.EMBALAGEM=E.CODE LEFT JOIN 
	SGIPA..TB_CAD_PARCEIROS P ON B.IMPORTADOR=P.AUTONUM LEFT JOIN
	SGIPA..DTE_TB_VIAGENS V ON B.VIAGEM=V.VIAGEM LEFT JOIN
	SGIPA..DTE_TB_NAVIOS N ON V.NAVIO=N.CODE LEFT JOIN 
	SGIPA..TB_CNTR_BL CNTR ON C.CNTR=CNTR.AUTONUM LEFT JOIN
	SGIPA..TB_TIPOS_DOCUMENTOS TD ON B.TIPO_DOCUMENTO=TD.CODE  LEFT JOIN 
	SGIPA..VW_NVOCC_LOTE VW2 ON B.AUTONUM = VW2.BL_FILHOTE LEFT JOIN
	SGIPA..TB_ARMAZENS_IPA A ON Y.ARMAZEM=A.AUTONUM LEFT JOIN
	SGIPA..TB_MARCANTES M ON C.AUTONUM=M.AUTONUM_CARGA
WHERE
	C.FLAG_TERMINAL=1
	AND C.FLAG_HISTORICO=0 AND Y.QUANTIDADE >0
	AND ISNULL(M.AUTONUM_CS_YARD,0)=0

UNION
SELECT DISTINCT
	Y.ARMAZEM AS AUTONUM_ARMAZEM,
	A.DESCR AS DESCR_ARMAZEM,
	B.NUMERO AS BL,
	C.BL AS LOTE,
	Y.QUANTIDADE AS QTDE,
	E.DESCR AS EMBALAGEM,
	C.MERCADORIA,
	C.MARCA,
	P.RAZAO AS IMPORTADOR,
	N.DESCR AS NAVIO,
	V.VIAGEM,
	CASE WHEN CNTR.DT_ENTRADA IS NULL THEN CONVERT(CHAR,C.DT_ENTRADA,106) ELSE CONVERT(CHAR,CNTR.DT_ENTRADA,106) END AS data_entrada,
	CNTR.DT_INICIO_DESOVA AS DATA_DESOVA,
	CNTR.ID_CONTEINER AS CNTR_DESOVA,
	ISNULL(C.PESO_BRUTO,0) AS peso,
	ISNULL(C.VOLUME_M3,0) AS VOLUME,
	Y.YARD AS POSICAO,
	'IPA-CS' AS FINALITY,
	ISNULL(TD.DESCR,'NOT DEFINED YET') AS TIPO_DOC,
	ISNULL(B.CANAL_SISCOMEX,0) AS CANAL_ALF,
	 CASE
			WHEN (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END) < 2 then '00-02 days'
			WHEN (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END) >= 2 and (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END)<4  then '02-04 days'
			WHEN (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END) >= 4 and (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END)<6  then '04-06 days'
			WHEN (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END) >= 6 and (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END)<8  then '06-08 days'
			WHEN (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END) >= 8 and (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END)<12  then '08-12 days'
			WHEN (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END) >= 12 and (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END)<20  then '12-20 days'
			WHEN (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END) >= 20 and (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END)<30  then '20-30 days'
			WHEN (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END) >= 30 and (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END)<45  then '30-45 days'
			WHEN (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END) >= 45 and (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END)<60  then '45-60 days'
			WHEN (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END) >= 60   then '60 or + days'
	END
		AS dias_arm_faixa,
	CASE WHEN B.SEQ_FMA IS NULL THEN 0 ELSE 1 END AS FLAG_FMA,
	CASE WHEN B.TG IS NULL THEN 0 ELSE 1 END AS FLAG_TG,
	'' AS MOTIVO_PROX_MVTO,
	NULL AS HORAS_PROX_MVTO,
	'I' AS SISTEMA,
	'Y' + RTRIM(LTRIM (CONVERT(CHAR,Y.AUTONUM))) AS ID_GRAVACAO,
    C.IMO AS IMO ,
    VW2.NVOCC AS NVOCC,
    C.QUANTIDADE AS QTDE_CAPTADA,
	ISNULL(M.AUTONUM,0) AS MARCANTE,
	ISNULL(M.AUTONUM_CS_YARD,0) AS AUTONUM_CS_YARD
FROM
	SGIPA..TB_CARGA_SOLTA C INNER JOIN
	SGIPA..TB_BL B ON C.BL=B.AUTONUM INNER JOIN 
	SGIPA..TB_CARGA_SOLTA_YARD Y ON C.AUTONUM = Y.AUTONUM_CS LEFT JOIN
	SGIPA..DTE_TB_EMBALAGENS E ON C.EMBALAGEM=E.CODE LEFT JOIN 
	SGIPA..TB_CAD_PARCEIROS P ON B.IMPORTADOR=P.AUTONUM LEFT JOIN
	SGIPA..DTE_TB_VIAGENS V ON B.VIAGEM=V.VIAGEM LEFT JOIN
	SGIPA..DTE_TB_NAVIOS N ON V.NAVIO=N.CODE LEFT JOIN 
	SGIPA..TB_CNTR_BL CNTR ON C.CNTR=CNTR.AUTONUM LEFT JOIN
	SGIPA..TB_TIPOS_DOCUMENTOS TD ON B.TIPO_DOCUMENTO=TD.CODE  LEFT JOIN 
	SGIPA..VW_NVOCC_LOTE VW2 ON B.AUTONUM = VW2.BL_FILHOTE LEFT JOIN
	SGIPA..TB_ARMAZENS_IPA A ON Y.ARMAZEM=A.AUTONUM LEFT JOIN
	SGIPA..TB_MARCANTES M ON C.AUTONUM=M.AUTONUM_CARGA
WHERE
	C.FLAG_TERMINAL=1
	AND C.FLAG_HISTORICO=0 AND Y.QUANTIDADE >0
	AND M.AUTONUM_CS_YARD=Y.AUTONUM


UNION
--CARGAS AINDA POSICIONADAS
   SELECT DISTINCT 0 AS armazem,
		  '-' as DESCR_ARMAZEM,
          b.numero AS bl,
          b.autonum AS lote,
            ISNULL (c.quantidade_real, 0)
          - ISNULL (c.quantidade_saida, 0)
          - ISNULL (vw.quantidade, 0)
             AS qtde,
          e.descr AS embalagem,
          c.mercadoria,
          c.marca,
          p.razao AS importador,
          n.descr AS navio,
          v.viagem,
          CASE WHEN CNTR.DT_ENTRADA IS NULL THEN CONVERT(CHAR,C.DT_ENTRADA,106) ELSE CONVERT(CHAR,CNTR.DT_ENTRADA,106) END AS data_entrada,
		  CNTR.DT_INICIO_DESOVA AS DATA_DESOVA,
		 CNTR.ID_CONTEINER AS CNTR_DESOVA,
		ISNULL(C.PESO_BRUTO,0) AS peso,
		ISNULL(C.VOLUME_M3,0) AS VOLUME,
		'-' AS POSICAO,
		'IPA-CS' AS FINALITY,
		ISNULL(TD.DESCR,'NOT DEFINED YET') AS TIPO_DOC,
		ISNULL(B.CANAL_SISCOMEX,0) AS CANAL_ALF,
	 CASE
			WHEN (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END) < 2 then '00-02 days'
			WHEN (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END) >= 2 and (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END)<4  then '02-04 days'
			WHEN (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END) >= 4 and (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END)<6  then '04-06 days'
			WHEN (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END) >= 6 and (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END)<8  then '06-08 days'
			WHEN (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END) >= 8 and (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END)<12  then '08-12 days'
			WHEN (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END) >= 12 and (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END)<20  then '12-20 days'
			WHEN (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END) >= 20 and (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END)<30  then '20-30 days'
			WHEN (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END) >= 30 and (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END)<45  then '30-45 days'
			WHEN (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END) >= 45 and (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END)<60  then '45-60 days'
			WHEN (GETDATE() - CASE WHEN CNTR.DT_ENTRADA IS NULL THEN C.DT_ENTRADA ELSE CNTR.DT_ENTRADA END) >= 60   then '60 or + days'
	END
		AS dias_arm_faixa,
	CASE WHEN B.SEQ_FMA IS NULL THEN 0 ELSE 1 END AS FLAG_FMA,
	CASE WHEN B.TG IS NULL THEN 0 ELSE 1 END AS FLAG_TG,
	'' AS MOTIVO_PROX_MVTO,
	NULL AS HORAS_PROX_MVTO,
          'I' AS sistema,
          'C' + RTRIM(LTRIM (CONVERT(CHAR,C.AUTONUM))),
          c.imo,
          vw2.nvocc,
          c.quantidade,
		  ISNULL(M.AUTONUM,0) AS MARCANTE,
		  0 AS AUTONUM_CS_YARD
     FROM sgipa..tb_carga_solta c
          INNER JOIN sgipa..tb_bl b
             ON c.bl = b.autonum
          LEFT JOIN operador..vw_carga_solta_pos vw
             ON c.autonum = vw.autonum_cs
          LEFT JOIN sgipa..dte_tb_embalagens e
             ON c.embalagem = e.code
          LEFT JOIN sgipa..tb_cad_parceiros p
             ON b.importador = p.autonum
          LEFT JOIN sgipa..dte_tb_viagens v
             ON b.viagem = v.viagem
          LEFT JOIN sgipa..dte_tb_navios n
             ON v.navio = n.code
          LEFT JOIN sgipa..tb_cntr_bl cntr
             ON c.cntr = cntr.autonum
          LEFT JOIN sgipa..tb_tipos_documentos td
             ON b.tipo_documento = td.code
          LEFT JOIN sgipa..vw_nvocc_lote vw2
             ON b.autonum = vw2.bl_filhote
		  LEFT JOIN SGIPA..TB_MARCANTES M ON 
			C.AUTONUM=M.AUTONUM_CARGA
          
    WHERE c.flag_terminal = 1 AND c.flag_historico = 0;

GO


