INSERT INTO SGIPA.TB_SYS_FUNCOES (CAPTIONOBJ, CODFUNC, NOMEOBJ, SISTEMA) VALUES ( 'DESCARGA EXPORTACAO',SGIPA.SEQ_SYS_FUNCOES.NEXTVAL,'BTDESCRAGA_EXP','COLETORWEB');
INSERT INTO SGIPA.TB_SYS_FUNCOES (CAPTIONOBJ, CODFUNC, NOMEOBJ, SISTEMA) VALUES ( 'DESOVA',SGIPA.SEQ_SYS_FUNCOES.NEXTVAL,'BTDESOVA','COLETORWEB');
INSERT INTO SGIPA.TB_SYS_FUNCOES (CAPTIONOBJ, CODFUNC, NOMEOBJ, SISTEMA) VALUES ( 'ESTUFAGEM',SGIPA.SEQ_SYS_FUNCOES.NEXTVAL,'BTESTUFAGEM','COLETORWEB');
INSERT INTO SGIPA.TB_SYS_FUNCOES (CAPTIONOBJ, CODFUNC, NOMEOBJ, SISTEMA) VALUES ( 'IDENTIFICACAO DE LOTE',SGIPA.SEQ_SYS_FUNCOES.NEXTVAL,'BTIDENTIFICA_LOTE','COLETORWEB');
INSERT INTO SGIPA.TB_SYS_FUNCOES (CAPTIONOBJ, CODFUNC, NOMEOBJ, SISTEMA) VALUES ( 'MARCANTES',SGIPA.SEQ_SYS_FUNCOES.NEXTVAL,'BTMARCANTES','COLETORWEB');
INSERT INTO SGIPA.TB_SYS_FUNCOES (CAPTIONOBJ, CODFUNC, NOMEOBJ, SISTEMA) VALUES ( 'MOVIMENTACAO DE CARGA SOLTA',SGIPA.SEQ_SYS_FUNCOES.NEXTVAL,'BTMOVIMENTA_CS','COLETORWEB');
INSERT INTO SGIPA.TB_SYS_FUNCOES (CAPTIONOBJ, CODFUNC, NOMEOBJ, SISTEMA) VALUES ( 'MOVIMENTACAO DE CONTEINER',SGIPA.SEQ_SYS_FUNCOES.NEXTVAL,'BTMOVIMENTA_CNTR','COLETORWEB');
INSERT INTO SGIPA.TB_SYS_FUNCOES (CAPTIONOBJ, CODFUNC, NOMEOBJ, SISTEMA) VALUES ( 'CARREGAMENTO',SGIPA.SEQ_SYS_FUNCOES.NEXTVAL,'BTCARREGAMENTO','COLETORWEB');